language: python

python:
    - "2.7"

branches:
    only:
        - master
        - solutions

install:
    - python setup.py install

script:
    - cd tests && nosetests -v -s 

notifications:
    email: false
